import { Resend } from 'resend';
import { config } from '../config/index';

export class EmailService {
  private resend: Resend;

  constructor() {
    this.resend = new Resend(config.resend.apiKey);
  }

  async sendDailyDigest(jobs: any[]): Promise<void> {
    const date = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    const subject = `🚀 Your Daily Job Matches — ${date} — ${jobs.length} Jobs Found`;

    const html = this.generateHtml(jobs);

    try {
      await this.resend.emails.send({
        from: config.resend.fromEmail,
        to: config.resend.toEmail,
        subject,
        html,
      });
      console.log(`Email digest sent to ${config.resend.toEmail}`);
    } catch (error) {
      console.error('Error sending email digest:', error);
    }
  }

  private generateHtml(jobs: any[]): string {
    const jobRows = jobs.map((job, index) => `
      <div style="margin-bottom: 30px; border-bottom: 1px solid #eee; padding-bottom: 20px;">
        <h3 style="margin: 0; color: #1a73e8;">${index + 1}. ${job.title}</h3>
        <p style="margin: 5px 0; font-weight: bold;">${job.company} | ${job.location} | Score: ${Math.round(job.finalScore * 100)}</p>
        <p style="margin: 10px 0; color: #555;">${job.explanation?.summary || 'No summary available'}</p>
        <p style="margin: 10px 0;"><strong>Skills Overlap:</strong> ${job.explanation?.skillsOverlap?.join(', ') || 'N/A'}</p>
        <a href="${job.url}" style="display: inline-block; background: #1a73e8; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; margin-top: 10px;">Apply Now</a>
      </div>
    `).join('');

    return `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <h1 style="color: #1a73e8;">Daily Job Matches</h1>
        <p>We found ${jobs.length} highly relevant jobs matching your profile today.</p>
        <hr style="border: 0; border-top: 2px solid #1a73e8; margin: 20px 0;" />
        ${jobRows}
        <p style="font-size: 12px; color: #999; margin-top: 40px;">
          Generated by AI Job Finder. To update your preferences, please edit your profile text.
        </p>
      </div>
    `;
  }
}
